-- create_db.sql
CREATE TABLE events (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title VARCHAR(100) NOT NULL,
  date DATE NOT NULL,
  location VARCHAR(100),
  quota INTEGER NOT NULL
);

CREATE TABLE participants (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  event_id INTEGER NOT NULL,
  FOREIGN KEY (event_id) REFERENCES events(id)
);
